/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  Assertions,
  AssertionsInterface,
} from "../../../contracts/libraries/Assertions";

const _abi = [
  {
    inputs: [
      {
        internalType: "int256",
        name: "_x",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "_y",
        type: "int256",
      },
    ],
    name: "IntNotGreaterOrEqualThan",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "_x",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "_y",
        type: "int256",
      },
    ],
    name: "IntNotGreaterThan",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "_x",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "_y",
        type: "int256",
      },
    ],
    name: "IntNotLesserOrEqualThan",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "_x",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "_y",
        type: "int256",
      },
    ],
    name: "IntNotLesserThan",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_y",
        type: "uint256",
      },
    ],
    name: "NotGreaterOrEqualThan",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_y",
        type: "uint256",
      },
    ],
    name: "NotGreaterThan",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_y",
        type: "uint256",
      },
    ],
    name: "NotLesserOrEqualThan",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_y",
        type: "uint256",
      },
    ],
    name: "NotLesserThan",
    type: "error",
  },
  {
    inputs: [],
    name: "NullAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "NullAmount",
    type: "error",
  },
] as const;

const _bytecode =
  "0x602d6037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea164736f6c6343000814000a";

type AssertionsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AssertionsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Assertions__factory extends ContractFactory {
  constructor(...args: AssertionsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Assertions & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Assertions__factory {
    return super.connect(runner) as Assertions__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AssertionsInterface {
    return new Interface(_abi) as AssertionsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Assertions {
    return new Contract(address, _abi, runner) as unknown as Assertions;
  }
}
